# Site settings
title: PhatBoyG.com
email: chris@phatboyg.com
description: > # this means to ignore newlines until "baseurl:"
  Software Development, .NET, Messaging, Distributed Applications, Service Oriented Architecture,
  MassTransit, Topshelf, Open Source
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.phatboyg.com" # the base hostname & protocol for your site
twitter_username: PhatBoyG
github_username:  PhatBoyG

# Build settings
markdown: kramdown
highlighter: pygments
